apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kit-gateway
  namespace: {{ENVIRONMENT}}
  labels:
    app: kit-gateway
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: kit-gateway-tls`
    hosts:
      - {{GATEWAY_HOSTNAME}}
  rules:
  - host: {{GATEWAY_HOSTNAME}}
    http:
      paths:
      - path: /
        backend:
          serviceName: kit-gateway
          servicePort: api