apiVersion: v1
kind: Service
metadata:
  name: kit-gateway
  namespace: {{NAMESPACE}}
  labels:
    app: kit-gateway
spec:
  ports:
  - name: api
    port: 3000
    targetPort: api
    protocol: TCP
  selector:
    app: kit-gateway