apiVersion: v1
kind: Service
metadata:
  name: kit-crud
  namespace: {{ENVIRONMENT}}
  labels:
    app: kit-crud
spec:
  ports:
  - name: grpc
    port: 8082
    targetPort: grpc
    protocol: TCP
  selector:
    app: kit-crud